
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "CrearSeguimientoCertificadorResponse", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CrearSeguimientoCertificadorResponse", namespace = "http://amnetgov.com/")

public class CrearSeguimientoCertificadorResponse {

    @XmlElement(name = "CrearSeguimientoCertificadorResult", namespace = "http://amnetgov.com/")
    private java.lang.String CrearSeguimientoCertificadorResult;

    public java.lang.String getCrearSeguimientoCertificadorResult() {
        return this.CrearSeguimientoCertificadorResult;
    }

    public void setCrearSeguimientoCertificadorResult(java.lang.String newCrearSeguimientoCertificadorResult)  {
        this.CrearSeguimientoCertificadorResult = newCrearSeguimientoCertificadorResult;
    }

}

