
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "RegistroExamenTemporal", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroExamenTemporal", namespace = "http://amnetgov.com/", propOrder = {"UsuarioServicio", "ContrasenaServicio", "IdSeguimiento", "EstadoExamen", "ResultadoExamen", "Obervaciones", "Detalle"})

public class RegistroExamenTemporal {

    @XmlElement(name = "UsuarioServicio", namespace = "http://amnetgov.com/")
    private java.lang.String UsuarioServicio;
    @XmlElement(name = "ContrasenaServicio", namespace = "http://amnetgov.com/")
    private java.lang.String ContrasenaServicio;
    @XmlElement(name = "IdSeguimiento", namespace = "http://amnetgov.com/")
    private java.lang.String IdSeguimiento;
    @XmlElement(name = "EstadoExamen", namespace = "http://amnetgov.com/")
    private int EstadoExamen;
    @XmlElement(name = "ResultadoExamen", namespace = "http://amnetgov.com/")
    private int ResultadoExamen;
    @XmlElement(name = "Obervaciones", namespace = "http://amnetgov.com/")
    private java.lang.String Obervaciones;
    @XmlElement(name = "Detalle", namespace = "http://amnetgov.com/")
    private com.amnetgov.SpecialistTestResultList Detalle;

    public java.lang.String getUsuarioServicio() {
        return this.UsuarioServicio;
    }

    public void setUsuarioServicio(java.lang.String newUsuarioServicio)  {
        this.UsuarioServicio = newUsuarioServicio;
    }

    public java.lang.String getContrasenaServicio() {
        return this.ContrasenaServicio;
    }

    public void setContrasenaServicio(java.lang.String newContrasenaServicio)  {
        this.ContrasenaServicio = newContrasenaServicio;
    }

    public java.lang.String getIdSeguimiento() {
        return this.IdSeguimiento;
    }

    public void setIdSeguimiento(java.lang.String newIdSeguimiento)  {
        this.IdSeguimiento = newIdSeguimiento;
    }

    public int getEstadoExamen() {
        return this.EstadoExamen;
    }

    public void setEstadoExamen(int newEstadoExamen)  {
        this.EstadoExamen = newEstadoExamen;
    }

    public int getResultadoExamen() {
        return this.ResultadoExamen;
    }

    public void setResultadoExamen(int newResultadoExamen)  {
        this.ResultadoExamen = newResultadoExamen;
    }

    public java.lang.String getObervaciones() {
        return this.Obervaciones;
    }

    public void setObervaciones(java.lang.String newObervaciones)  {
        this.Obervaciones = newObervaciones;
    }

    public com.amnetgov.SpecialistTestResultList getDetalle() {
        return this.Detalle;
    }

    public void setDetalle(com.amnetgov.SpecialistTestResultList newDetalle)  {
        this.Detalle = newDetalle;
    }

}

