
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "SeleccionarProcesoPorIdentificacionAspirante", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeleccionarProcesoPorIdentificacionAspirante", namespace = "http://amnetgov.com/", propOrder = {"UsuarioServicio", "ContrasenaServicio", "TipoIdentificacion", "NumeroIdentificacion"})

public class SeleccionarProcesoPorIdentificacionAspirante {

    @XmlElement(name = "UsuarioServicio", namespace = "http://amnetgov.com/")
    private java.lang.String UsuarioServicio;
    @XmlElement(name = "ContrasenaServicio", namespace = "http://amnetgov.com/")
    private java.lang.String ContrasenaServicio;
    @XmlElement(name = "TipoIdentificacion", namespace = "http://amnetgov.com/")
    private java.lang.String TipoIdentificacion;
    @XmlElement(name = "NumeroIdentificacion", namespace = "http://amnetgov.com/")
    private java.lang.String NumeroIdentificacion;

    public java.lang.String getUsuarioServicio() {
        return this.UsuarioServicio;
    }

    public void setUsuarioServicio(java.lang.String newUsuarioServicio)  {
        this.UsuarioServicio = newUsuarioServicio;
    }

    public java.lang.String getContrasenaServicio() {
        return this.ContrasenaServicio;
    }

    public void setContrasenaServicio(java.lang.String newContrasenaServicio)  {
        this.ContrasenaServicio = newContrasenaServicio;
    }

    public java.lang.String getTipoIdentificacion() {
        return this.TipoIdentificacion;
    }

    public void setTipoIdentificacion(java.lang.String newTipoIdentificacion)  {
        this.TipoIdentificacion = newTipoIdentificacion;
    }

    public java.lang.String getNumeroIdentificacion() {
        return this.NumeroIdentificacion;
    }

    public void setNumeroIdentificacion(java.lang.String newNumeroIdentificacion)  {
        this.NumeroIdentificacion = newNumeroIdentificacion;
    }

}

