
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "SeleccionarImagenesProcesoResponse", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeleccionarImagenesProcesoResponse", namespace = "http://amnetgov.com/")

public class SeleccionarImagenesProcesoResponse {

    @XmlElement(name = "SeleccionarImagenesProcesoResult", namespace = "http://amnetgov.com/")
    private com.amnetgov.entities.BiometricData SeleccionarImagenesProcesoResult;

    public com.amnetgov.entities.BiometricData getSeleccionarImagenesProcesoResult() {
        return this.SeleccionarImagenesProcesoResult;
    }

    public void setSeleccionarImagenesProcesoResult(com.amnetgov.entities.BiometricData newSeleccionarImagenesProcesoResult)  {
        this.SeleccionarImagenesProcesoResult = newSeleccionarImagenesProcesoResult;
    }

}

