
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "SeleccionarProcesoPorIdentificacionAspiranteComboResponse", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeleccionarProcesoPorIdentificacionAspiranteComboResponse", namespace = "http://amnetgov.com/")

public class SeleccionarProcesoPorIdentificacionAspiranteComboResponse {

    @XmlElement(name = "SeleccionarProcesoPorIdentificacionAspiranteComboResult", namespace = "http://amnetgov.com/")
    private long SeleccionarProcesoPorIdentificacionAspiranteComboResult;

    public long getSeleccionarProcesoPorIdentificacionAspiranteComboResult() {
        return this.SeleccionarProcesoPorIdentificacionAspiranteComboResult;
    }

    public void setSeleccionarProcesoPorIdentificacionAspiranteComboResult(long newSeleccionarProcesoPorIdentificacionAspiranteComboResult)  {
        this.SeleccionarProcesoPorIdentificacionAspiranteComboResult = newSeleccionarProcesoPorIdentificacionAspiranteComboResult;
    }

}

