
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "SolicitarIdentificadorSeguimientoResponse", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolicitarIdentificadorSeguimientoResponse", namespace = "http://amnetgov.com/")

public class SolicitarIdentificadorSeguimientoResponse {

    @XmlElement(name = "SolicitarIdentificadorSeguimientoResult", namespace = "http://amnetgov.com/")
    private java.lang.String SolicitarIdentificadorSeguimientoResult;

    public java.lang.String getSolicitarIdentificadorSeguimientoResult() {
        return this.SolicitarIdentificadorSeguimientoResult;
    }

    public void setSolicitarIdentificadorSeguimientoResult(java.lang.String newSolicitarIdentificadorSeguimientoResult)  {
        this.SolicitarIdentificadorSeguimientoResult = newSolicitarIdentificadorSeguimientoResult;
    }

}

