
package com.amnetgov.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.5
 * Tue Apr 12 18:21:06 IDT 2016
 * Generated source version: 3.0.5
 */

@XmlRootElement(name = "SolicitarResultadoIdentificadorSeguimientoResponse", namespace = "http://amnetgov.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolicitarResultadoIdentificadorSeguimientoResponse", namespace = "http://amnetgov.com/")

public class SolicitarResultadoIdentificadorSeguimientoResponse {

    @XmlElement(name = "SolicitarResultadoIdentificadorSeguimientoResult", namespace = "http://amnetgov.com/")
    private com.amnetgov.entities.BiometricAuthResult SolicitarResultadoIdentificadorSeguimientoResult;

    public com.amnetgov.entities.BiometricAuthResult getSolicitarResultadoIdentificadorSeguimientoResult() {
        return this.SolicitarResultadoIdentificadorSeguimientoResult;
    }

    public void setSolicitarResultadoIdentificadorSeguimientoResult(com.amnetgov.entities.BiometricAuthResult newSolicitarResultadoIdentificadorSeguimientoResult)  {
        this.SolicitarResultadoIdentificadorSeguimientoResult = newSolicitarResultadoIdentificadorSeguimientoResult;
    }

}

