
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.amnetgov.ws;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.UUID;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import com.amnetgov.BiometricAuthDetailsList;
import com.amnetgov.ConsultarResultadoSeguimientoCertificadorResultado;
import com.amnetgov.SeleccionarResultadoCertificadorResultado;
import com.amnetgov.ServicioProcesoSoap;
import com.amnetgov.SpecialistTestResultList;
import com.amnetgov.entities.BasicDataProcess;
import com.amnetgov.entities.BiometricAuthDetails;
import com.amnetgov.entities.BiometricAuthResult;
import com.amnetgov.entities.BiometricData;
import com.amnetgov.entities.PersonalBasicInfo;
import com.amnetgov.entities.PersonalOtherInfo;
import com.amnetgov.enums.Answer;
import com.amnetgov.enums.Category;
import com.amnetgov.enums.ProcessStatus;
import com.amnetgov.enums.StateStatus;
import com.amnetgov.enums.VvEnums;
import com.amnetgov.exception.ErrorDetailsBean;
import com.amnetgov.exception.VvException;
import com.amnetgov.model.InitialCrcData;
import com.google.gson.Gson;

/**
 * This class was generated by Apache CXF 3.1.4 2016-02-11T15:59:01.364-08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(serviceName = "ServicioProceso", portName = "Soap12ImplPort", targetNamespace = "http://amnetgov.com/", endpointInterface = "com.amnetgov.ServicioProcesoSoap")
// @OutFaultInterceptors(classes = {ValidationInterceptor.class})
@BindingType(value = "http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class Soap12Impl implements ServicioProcesoSoap {

	@Resource
	WebServiceContext webServiceContext;

	// private static final Logger LOGGER =
	// Logger.getLogger(Soap12Impl.class.getName());

	private static final Logger logger = LogManager.getLogger(Soap12Impl.class.getName());

	private DataSource dataSource;
	private InitialContext ctx1 = null;

	public Soap12Impl() throws NamingException {
		ctx1 = new InitialContext();
		dataSource = (DataSource) ctx1.lookup("java:/PostgresDS");
	}

	// close connection
	private void closeConnection(Connection conn, ResultSet resultSet, PreparedStatement preStatement) {
		try {
			if (resultSet != null)
				resultSet.close();
			if (preStatement != null)
				preStatement.close();
			if (conn != null)
				conn.close();
		} catch (SQLException ex) {
			System.out.println(ex.getMessage());
		}
	}
	
	private void detectCrc(Connection conn, InitialCrcData crcData) {
		ResultSet resultSet = null;
		PreparedStatement preStatement = null;
		/*
		 * STORING CRC ID WHERE OCCURES LAST EVENT
		 */
		try {
			preStatement = conn.prepareStatement(
					"UPDATE crc_schema.tservice_events SET crc_id=(SELECT tcrc.crc_id FROM crc_schema.tcrc WHERE tcrc.crc_user=? AND tcrc.crc_pass=?) "
					+ "WHERE tservice_events.event_id = (SELECT max(tservice_events.event_id) FROM crc_schema.tservice_events)");
			preStatement.setString(1, crcData.getCrcUser());
			preStatement.setString(2, crcData.getCrcPass());
			preStatement.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			closeConnection(null, resultSet, preStatement);

		}
	}

	/*
	 * GET INFO ABOUT EXCEPTION
	 */
	private VvException getAuthFault(Connection conn, int errorCode) {
		ResultSet resultSet = null;
		PreparedStatement preStatement = null;
		ErrorDetailsBean _faultBean = null;
		VvException _exception = null;
		try {
			preStatement = conn.prepareStatement("SELECT * FROM crc_schema.texception WHERE code_id=?");
			preStatement.setInt(1, errorCode);
			resultSet = preStatement.executeQuery();
			while (resultSet != null && resultSet.next()) {
				_faultBean = new ErrorDetailsBean();
				_faultBean.setErrorCode(errorCode);
				_faultBean.setErrorMessage(resultSet.getString("message"));
				_exception = new VvException(_faultBean.getErrorMessage(), _faultBean);
			}
		} catch (SQLException ex) {
			System.out.println(ex);
		} finally {
			closeConnection(null, resultSet, preStatement);
		}
		return _exception;
	}

	private VvException faultAsWarningEvent(int errorCode, InitialCrcData crcData) {
		Connection conn = null;
		ResultSet resultSet = null;
		PreparedStatement preStatement = null;
		ErrorDetailsBean _faultBean = null;
		VvException _exception = null;
		try {
			conn = dataSource.getConnection();
			preStatement = conn.prepareStatement(
					"SELECT *,tcrc.crc_name,tcrc.crc_latitude,crc_longtitude FROM crc_schema.texception WHERE code_id=?");
			preStatement.setInt(1, errorCode);
			resultSet = preStatement.executeQuery();
			while (resultSet != null && resultSet.next()) {
				_faultBean = new ErrorDetailsBean();
				_faultBean.setErrorCode(errorCode);
				_faultBean.setErrorMessage("" + "CRC name:" + crcData.getCrcName() + "\nCRC Municipal Location:"
						+ crcData.getMunicipalLocation() + "\nCRC Address :" + crcData.getAddress() + "\nCRC Latitude :"
						+ crcData.getCrcLatitude() + "\nCRC Longtitude :" + crcData.getCrcLongtitude()
						+ "\nCRC Latitude :" + crcData.getCrcLatitude() + "\nException message : "
						+ resultSet.getString("message"));
				_exception = new VvException(_faultBean.getErrorMessage(), _faultBean);
			}
		} catch (SQLException ex) {
			logger.fatal(_faultBean.getErrorMessage(), _exception);
			detectCrc(conn,crcData);
			throw new RuntimeException(ex);
		} finally {
			logger.warn(_faultBean.getErrorCode(), _exception);
			detectCrc(conn,crcData);
			closeConnection(conn, resultSet, preStatement);
		}
		return _exception;
	}

	private VvException faultAsErrorEvent(int errorCode, InitialCrcData crcData) {
		Connection conn = null;
		ResultSet resultSet = null;
		PreparedStatement preStatement = null;
		ErrorDetailsBean _faultBean = null;
		VvException _exception = null;
		try {
			conn = dataSource.getConnection();
			preStatement = conn.prepareStatement("SELECT * FROM crc_schema.texception WHERE code_id=?");
			preStatement.setInt(1, errorCode);
			resultSet = preStatement.executeQuery();
			while (resultSet != null && resultSet.next()) {
				_faultBean = new ErrorDetailsBean();
				_faultBean.setErrorCode(errorCode);
				_faultBean.setErrorMessage(resultSet.getString("message"));
				_exception = new VvException(_faultBean.getErrorMessage(), _faultBean);
			}
		} catch (SQLException ex) {
			logger.fatal(_faultBean.getErrorMessage(), _exception);
			detectCrc(conn,crcData);
			throw new RuntimeException(ex);
		} finally {
			logger.error(_faultBean.getErrorCode(), _exception);
			detectCrc(conn,crcData);
			closeConnection(conn, resultSet, preStatement);
		}
		return _exception;
	}

	/*
	 * VALIDATE SERVICE CALL FROM CRC
	 */
	private boolean validateCRC(Connection conn, InitialCrcData crcData) {
		logger.info("Executing operation findCRC in VvDataProcess");
		boolean active = false;
		boolean found = false;
		ResultSet resultSet = null;
		PreparedStatement preStatement = null;
		double returnedCrcLong = VvEnums.DEFAULT.getValue();
		double returnedCrcLat = VvEnums.DEFAULT.getValue();
		String validDistance = "";
		String returnedCrcUser = "";
		String returnedCrcPass = "";
		if ((!crcData.getCrcUser().isEmpty() && crcData.getCrcUser() != null)
				&& (!crcData.getCrcPass().isEmpty() && crcData.getCrcPass() != null))
			try {
				preStatement = conn.prepareStatement(
						"" + "SELECT tcrc.*,tconfig.param,tconfig.val " + "FROM crc_schema.tcrc,crc_schema.tconfig "
								+ "WHERE tcrc.crc_user=? AND tcrc.crc_pass=? AND tconfig.param=?");
				preStatement.setString(1, crcData.getCrcUser());
				preStatement.setString(2, crcData.getCrcPass());
				preStatement.setString(3, "max_crc_distance");
				resultSet = preStatement.executeQuery();
				while (resultSet != null && resultSet.next()) {
					returnedCrcUser = resultSet.getString("crc_user");
					returnedCrcPass = resultSet.getString("crc_pass");
					returnedCrcLong = resultSet.getDouble("crc_longtitude");
					returnedCrcLat = resultSet.getDouble("crc_latitude");
					crcData.setCrcStatus(resultSet.getInt("status"));
					validDistance = resultSet.getString("val");
				}
				if (validDistance == "" || validDistance.isEmpty()) {
					/*
					 * Max value for GRS distance is no configured
					 */
					faultAsErrorEvent(11005, crcData);
				}
				if (crcData.getCrcUser().equals(returnedCrcUser) && crcData.getCrcPass().equals(returnedCrcPass)) {
					found = true;
				}
				if (!found) {
					faultAsErrorEvent(11005, crcData);
				}
				if (crcData.getCrcStatus() == VvEnums.ACTIVE.getValue()) {
					active = true;
				}
				if (!active) {
					faultAsErrorEvent(11005, crcData);
				}
				/*
				 * if (crcData.getCrcLatitude() == 1000 &&
				 * crcData.getCrcLongtitude() == 1000) {
				 * faultAsErrorEvent(11000, crcData); } if
				 * (crcData.getCrcLatitude() == 1001 &&
				 * crcData.getCrcLongtitude() == 1001) {
				 * faultAsErrorEvent(11001, crcData); }
				 */
				/*
				 * LanGps gps = new LanGps(); Double crcGpsResult =
				 * gps.distanceInMeter(returnedCrcLat, crcData.getCrcLatitude(),
				 * returnedCrcLong, crcData.getCrcLongtitude(), 0, 0); if
				 * (crcGpsResult >= Double.parseDouble(validDistance)) {
				 * faultAsWarningEvent(11002, crcData); }
				 */
			} catch (SQLException ex) {
				logger.fatal(ex.getMessage(), ex);
				detectCrc(conn,crcData);
				throw new RuntimeException(ex);
			} finally {
				closeConnection(null, resultSet, preStatement);
			}
		return found && active; // must return valid instead found
	}

	/*
	 * checking if Candidate process has finished 4 specialist's tests as
	 * mandatory for Certificator validation
	 */
	private void checkAndChangeStateOfProcessForCertificator(Connection conn, String endSeguimento) {
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		try {
			prepareStmt = conn.prepareStatement("SELECT process_id,COUNT(questions_result) AS tests"
					+ " FROM crc_schema.ttest WHERE estado ='4' AND process_id IN "
					+ "(SELECT process_id FROM crc_schema.ttest WHERE end_seg =?::uuid) " + "GROUP BY process_id");
			prepareStmt.setString(1, endSeguimento);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				if (resultSet.getInt("tests") == 4) {
					prepareStmt = conn.prepareStatement("UPDATE crc_schema.tprocess SET estado=? WHERE process_id = ?");
					prepareStmt.setString(1, ProcessStatus.VERPRB.name());
					prepareStmt.setLong(2, resultSet.getLong("process_id"));
					if (prepareStmt.executeUpdate() == VvEnums.UPDATED.getValue()) {
						System.out.println("The Candidate with process_id :+ " + resultSet.getLong("process_id")
								+ "  finished all Tests and his process status changed to \"VERPRB\" ");
					}
					prepareStmt.executeUpdate();
				}
			}
		} catch (SQLException e) {
			System.out.println(e.getMessage());
		} finally {
			closeConnection(null, resultSet, prepareStmt);
		}
	}

	/*
	 * TESTED 1 - seleccionarProcesoPorIdentificacionAspirante 3.2 RETURN
	 * PROCESS ID
	 */
	public long seleccionarProcesoPorIdentificacionAspirante(String usuarioServicio, String contrasenaServicio,
			String tipoIdentificacion, String numeroIdentificacion) {
		logger.info("Executing operation seleccionarProcesoPorIdentificacionAspirante");
		long processID = VvEnums.DEFAULT.getValue();
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12012);
			}
			prepareStmt = conn
					.prepareStatement("SELECT process_id " + "FROM crc_schema.tprocess " + "JOIN crc_schema.tcandidate "
							+ "ON crc_schema.tprocess.num_ident = crc_schema.tcandidate.num_ident "
							+ "WHERE crc_schema.tcandidate.num_ident =? AND tipo_ident=? "
							+ "ORDER BY process_id DESC LIMIT 1");
			prepareStmt.setString(1, numeroIdentificacion);
			prepareStmt.setString(2, tipoIdentificacion);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				processID = resultSet.getLong("process_id");
			}
			if (processID == VvEnums.DEFAULT.getValue()) {
				throw getAuthFault(conn, 12500);
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex.getMessage());
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return processID;
	}

	/*
	 * TESTED 2 - seleccionarProcesoDatosBasicos 3.3 - RETURNS BASIC PROCESS
	 * DATA -
	 */
	public PersonalBasicInfo seleccionarProcesoDatosBasicos(String usuarioServicio, String contrasenaServicio,
			long idProceso) {
		PersonalBasicInfo candidateBasicInfo = new PersonalBasicInfo();
		BasicDataProcess datosBasicos = null;
		GregorianCalendar gregorianCalendar = null;
		XMLGregorianCalendar xmlGregorianCalendar = null;
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		long organizationId = VvEnums.DEFAULT.getValue();
		long processOrganization = VvEnums.DEFAULT.getValue();
		logger.info("Executing operation seleccionarProcesoDatosBasicos");
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12013);
			}
			prepareStmt = conn.prepareStatement(
					"SELECT tcrc.organization_id FROM crc_schema.tcrc WHERE crc_user=? AND tcrc.crc_pass=?");
			prepareStmt.setString(1, usuarioServicio);
			prepareStmt.setString(2, contrasenaServicio);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				organizationId = resultSet.getLong("organization_id");
			}
			if (organizationId == VvEnums.DEFAULT.getValue()) {
				// Regular CRC Authentication fault
				throw getAuthFault(conn, 12013);
			}
			closeConnection(null, resultSet, prepareStmt);
			prepareStmt = conn
					.prepareStatement("SELECT tcandidate.*," + "tprocess.num_ident,tprocess.categoria,tprocess.tramite,"
							+ "tprocess.segundo_tramite,tprocess.segunda_categoria,tprocess.validacion_manual,tprocess.estado,tprocess.objectivo,tprocess.numero_evaluacion,tprocess.servicio,"
							+ "tcrc.crc_id,torganization.organization_id " + "FROM crc_schema.tcandidate "
							+ "JOIN crc_schema.tprocess ON crc_schema.tprocess.num_ident = crc_schema.tcandidate.num_ident "
							+ "JOIN crc_schema.tcrc ON crc_schema.tprocess.crc_id = crc_schema.tcrc.crc_id "
							+ "JOIN crc_schema.torganization ON torganization.organization_id = tcrc.organization_id "
							+ "AND tprocess.process_id=?");
			prepareStmt.setLong(1, idProceso);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				processOrganization = resultSet.getLong("organization_id");
				if (organizationId != processOrganization) {
					// Provided process belongs to another Organization
					closeConnection(conn, resultSet, prepareStmt);
					throw getAuthFault(conn, 12513);
				}
				datosBasicos = new BasicDataProcess();
				datosBasicos.setCategoria(resultSet.getString("categoria"));
				datosBasicos.setEstado(resultSet.getString("estado"));
				gregorianCalendar = new GregorianCalendar();
				gregorianCalendar.setTime(resultSet.getTimestamp("fec_registro"));
				xmlGregorianCalendar = DatatypeFactory.newInstance().newXMLGregorianCalendar(gregorianCalendar);
				datosBasicos.setFechaRegistro(xmlGregorianCalendar);
				// datosBasicos.setIdPersona(value);
				datosBasicos.setNombreAcompanante(resultSet.getString("nombre_acompanante"));
				datosBasicos.setObjetivo(resultSet.getInt("objectivo"));
				datosBasicos.setRangoInterno(resultSet.getLong("numero_evaluacion"));
				datosBasicos.setSegundaCategoria(resultSet.getString("segunda_categoria"));
				datosBasicos.setSegundoTramite(resultSet.getShort("segundo_tramite"));
				datosBasicos.setServicio(resultSet.getShort("servicio"));
				datosBasicos.setTelefonoAcompanante(resultSet.getString("telefono_acompanante"));
				datosBasicos.setTramite(resultSet.getShort("tramite"));
				datosBasicos.setValidacionManual(resultSet.getInt("validacion_manual"));
				candidateBasicInfo = new PersonalBasicInfo();
				candidateBasicInfo.setCodigoTipoIdentificacion(resultSet.getString("tipo_ident"));
				gregorianCalendar.setTime(resultSet.getTimestamp("fec_nacimiento"));
				xmlGregorianCalendar = DatatypeFactory.newInstance().newXMLGregorianCalendar(gregorianCalendar);
				candidateBasicInfo.setFechaNacimiento(xmlGregorianCalendar);
				candidateBasicInfo.setIdGradoEscolaridad(resultSet.getShort("grado_escolaridad"));
				candidateBasicInfo.setIdGrupoSanguinio(resultSet.getShort("grupo_sanguineo"));
				// candidateBasicInfo.setIdPersona(value);
				candidateBasicInfo.setLugarNacimiento(resultSet.getString("lugar_nacimiento"));
				candidateBasicInfo.setNumeroDocumento(resultSet.getString("num_ident"));
				candidateBasicInfo.setPrimerApellido(resultSet.getString("primer_apellido"));
				candidateBasicInfo.setPrimerNombre(resultSet.getString("primer_nombre"));
				candidateBasicInfo.setProcesoDatosBasicos(datosBasicos);
				candidateBasicInfo.setSegundoApellido(resultSet.getString("segundo_apellido"));
				candidateBasicInfo.setSegundoNombre(resultSet.getString("segundo_nombre"));
				candidateBasicInfo.setSexo(resultSet.getString("sexo"));
				candidateBasicInfo.setProcesoDatosBasicos(datosBasicos);
			}
			if (candidateBasicInfo.equals(null) || datosBasicos.equals(null)) {
				throw getAuthFault(conn, 12501);
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex.getMessage());
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return candidateBasicInfo;
	}

	/*
	 * TESTED 3 - seleccionarProcesoDatosComplementarios 3.4 - RETURNS OTHER
	 * PROCESS DATA
	 */
	public PersonalOtherInfo seleccionarProcesoDatosComplementarios(String usuarioServicio, String contrasenaServicio,
			long idProceso) {
		logger.info("Executing operation seleccionarProcesoDatosComplementarios");
		PersonalOtherInfo _returned = null;
		GregorianCalendar gregorianCalendar = new GregorianCalendar();
		XMLGregorianCalendar xmlGregorianCalendar = null;
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		long organizationId = VvEnums.DEFAULT.getValue();
		long processOrganization = VvEnums.DEFAULT.getValue();
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12014);
			}
			prepareStmt = conn.prepareStatement(
					"SELECT tcrc.organization_id FROM crc_schema.tcrc WHERE crc_user=? AND tcrc.crc_pass=?");
			prepareStmt.setString(1, usuarioServicio);
			prepareStmt.setString(2, contrasenaServicio);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				organizationId = resultSet.getLong("organization_id");
			}
			if (organizationId == VvEnums.DEFAULT.getValue()) {
				// Regular CRC Authentication fault
				throw getAuthFault(conn, 12013);
			}
			closeConnection(null, resultSet, prepareStmt);
			prepareStmt = conn
					.prepareStatement("SELECT tcandidate.*," + "tprocess.num_ident,tprocess.categoria,tprocess.tramite,"
							+ "tprocess.segundo_tramite,tprocess.segunda_categoria,tprocess.validacion_manual,tprocess.estado,tprocess.objectivo,tprocess.numero_evaluacion,tprocess.servicio,"
							+ "tcrc.crc_id,torganization.organization_id " + "FROM crc_schema.tcandidate "
							+ "JOIN crc_schema.tprocess ON crc_schema.tprocess.num_ident = crc_schema.tcandidate.num_ident "
							+ "JOIN crc_schema.tcrc ON crc_schema.tprocess.crc_id = crc_schema.tcrc.crc_id "
							+ "JOIN crc_schema.torganization ON torganization.organization_id = tcrc.organization_id "
							+ "AND tprocess.process_id=?");
			prepareStmt.setLong(1, idProceso);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				processOrganization = resultSet.getLong("organization_id");
				if (organizationId != processOrganization) {
					// Provided process belongs to another Organization
					throw getAuthFault(conn, 12513);
				}
				gregorianCalendar.setTime(resultSet.getTimestamp("fec_exp_documento"));
				xmlGregorianCalendar = DatatypeFactory.newInstance().newXMLGregorianCalendar(gregorianCalendar);
				_returned = new PersonalOtherInfo();
				_returned.setFecExpDocumeno(xmlGregorianCalendar);
				_returned.setLugExpDocumento(resultSet.getString("lug_exp_documento"));
				_returned.setDeptoResidencia(resultSet.getString("depto_residencia"));
				_returned.setMuniResidencia(resultSet.getString("muni_residencia"));
				_returned.setDireccion(resultSet.getString("direccion"));
				_returned.setTelefono(resultSet.getInt("telefono"));
				_returned.setMovil(resultSet.getString("movil"));
				_returned.setEmail(resultSet.getString("email"));
				_returned.setEstadoCivil(resultSet.getShort("estado_civil"));
				_returned.setEpsArs(resultSet.getInt("eps_ars"));
				_returned.setOcupacion(resultSet.getInt("ocupacion"));
				_returned.setIdPersona(Long.valueOf(resultSet.getString("num_ident")));
			}

			if (_returned == null) {
				throw getAuthFault(conn, 12502);
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex.getMessage());
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return _returned;
	}

	/*
	 * TESTED 4 - seleccionarImagenesProceso - 3.9 returns candidates pictures
	 */
	public BiometricData seleccionarImagenesProceso(String usuarioServicio, String contrasenaServicio, long idProceso) {
		logger.info("Executing operation seleccionarImagenesProceso");
		BiometricData _returned = null;
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		long organizationId = VvEnums.DEFAULT.getValue();
		long processOrganization = VvEnums.DEFAULT.getValue();
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12015);
			}
			prepareStmt = conn.prepareStatement(
					"SELECT tcrc.organization_id FROM crc_schema.tcrc WHERE crc_user=? AND tcrc.crc_pass=?");
			prepareStmt.setString(1, usuarioServicio);
			prepareStmt.setString(2, contrasenaServicio);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				organizationId = resultSet.getLong("organization_id");
			}
			if (organizationId == VvEnums.DEFAULT.getValue()) {
				// Regular CRC Authentication fault
				throw getAuthFault(conn, 12013);
			}
			closeConnection(null, resultSet, prepareStmt);
			prepareStmt = conn.prepareStatement(
					"SELECT tcandidate.*,tprocess.num_ident,tcrc.crc_id,torganization.organization_id "
							+ "FROM crc_schema.tcandidate "
							+ "JOIN crc_schema.tprocess ON crc_schema.tprocess.num_ident = crc_schema.tcandidate.num_ident "
							+ "JOIN crc_schema.tcrc ON crc_schema.tprocess.crc_id = crc_schema.tcrc.crc_id "
							+ "JOIN crc_schema.torganization ON torganization.organization_id = tcrc.organization_id "
							+ "AND tprocess.process_id=?");
			prepareStmt.setLong(1, idProceso);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				processOrganization = resultSet.getLong("organization_id");
				if (organizationId != processOrganization) {
					// Provided process belongs to another Organization
					closeConnection(conn, resultSet, prepareStmt);
					throw getAuthFault(conn, 12513);
				}
				_returned = new BiometricData();
				/*
				 * _returned.setFotografia(new
				 * String(resultSet.getString("photograph").getBytes("UTF-8"),
				 * "Windows-1252")); _returned.setHuellaIzq(new
				 * String(resultSet.getString("huella_izg").getBytes("UTF-8"),
				 * "Windows-1252")); _returned.setHuellaDer(new
				 * String(resultSet.getString("huella_der").getBytes("UTF-8"),
				 * "Windows-1252"));
				 */
				_returned.setFotografia(resultSet.getString("photograph"));
				_returned.setHuellaIzq(resultSet.getString("huella_izg"));
				_returned.setHuellaDer(resultSet.getString("huella_der"));
			}

			if (_returned.equals(null)) {
				throw getAuthFault(conn, 12503);
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex.getMessage());
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return _returned;

	}

	/*
	 * 4 - solicitarIdentificadorSeguimiento GENERATES SESSION ID returns (
	 * start || end if inicio parameter true || false ) - 3.5
	 */
	public String solicitarIdentificadorSeguimiento(String usuarioServicio, String contrasenaServicio,
			long numeroProceso, String rolEspecialista, String especialista, boolean inicio) {
		logger.info("Executing operation solicitarIdentificadorSeguimiento");
		String _returnedStrValue = null;
		boolean createdSeg = false;
		boolean allreadyDone = false;
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		int status = VvEnums.VERIFICATION_FAILED.getValue();
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12016);
			}

			/*
			 * Checking SPECIALIST's status if its 1 - ACTIVE ?
			 */
			prepareStmt = conn.prepareStatement("SELECT status FROM crc_schema.tpeople WHERE specialist_id=?::uuid");
			prepareStmt.setString(1, especialista);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				status = resultSet.getInt("status");
			}
			// Can't start test - Specialist not active
			if (status != VvEnums.ACTIVE.getValue()) {
				throw getAuthFault(conn, 12027);
			}

			/*
			 * when specialist's TEST STARTS
			 */
			if (inicio) {
				/*
				 * !!!! CHECKING IF OTHER TESTS WITH CURRENT PROCESS ID THAT
				 * WERE STARTED THEY ARE FINISHED -- !!!
				 */
				String startTest = "";
				String endTest = "";
				closeConnection(null, resultSet, prepareStmt);
				prepareStmt = conn
						.prepareStatement("SELECT start_seg,end_seg FROM crc_schema.ttest WHERE process_id=?");
				prepareStmt.setLong(1, numeroProceso);
				resultSet = prepareStmt.executeQuery();
				while (resultSet != null && resultSet.next()) {
					startTest = resultSet.getString("start_seg");
					endTest = resultSet.getString("end_seg");
					if (startTest != "" && (endTest == "" || endTest.isEmpty())) {
						throw getAuthFault(conn, 10008);
					}
				}
				closeConnection(null, resultSet, prepareStmt);
				prepareStmt = conn.prepareStatement(
						"INSERT INTO crc_schema.ttest  (process_id,specialist_id,role_specialist,start_seg) values(?,?::uuid,?::uuid,?) returning start_seg");
				prepareStmt.setLong(1, numeroProceso);
				prepareStmt.setString(2, especialista);
				prepareStmt.setString(3, rolEspecialista);
				prepareStmt.setObject(4, UUID.randomUUID());
				resultSet = prepareStmt.executeQuery();
				while (resultSet != null && resultSet.next()) {
					_returnedStrValue = resultSet.getString("start_seg");
					createdSeg = true;
				}
				closeConnection(conn, resultSet, prepareStmt);
				if (!createdSeg) {
					throw getAuthFault(conn, 12508);
				}
			}
			/*
			 * when specialist's TEST ENDS
			 */
			if (!inicio) {
				String sessionStart = "";
				/*
				 * _checkSQL - checks FIRST fingers validation 1=OK & test
				 * started before
				 */
				closeConnection(null, resultSet, prepareStmt);
				prepareStmt = conn.prepareStatement(
						"SELECT start_seg,end_seg,estado_ver_end,estado_ver_start FROM crc_schema.ttest WHERE process_id=? AND specialist_id=?::uuid");
				prepareStmt.setLong(1, numeroProceso);
				prepareStmt.setString(2, especialista);
				resultSet = prepareStmt.executeQuery();
				if (!resultSet.next()) {
					// not test found
					throw getAuthFault(conn, 12504);
				}
				sessionStart = resultSet.getString("start_seg");
				int firstValidationResult = resultSet.getInt("estado_ver_start");
				if (sessionStart == "") {
					// never started before so it can't be finished";
					throw getAuthFault(conn, 12505);
				}
				if (firstValidationResult == VvEnums.VERIFICATION_FAILED.getValue()) {
					// UNSUCCESSFUL fingers validation at beginning of
					// this
					// test";
					throw getAuthFault(conn, 12506);
				}
				if (firstValidationResult == VvEnums.PENDING.getValue()) {
					// DID NOT PERFORM fingers validation at beginning
					// of this
					// test";
					throw getAuthFault(conn, 12507);
				}
				_returnedStrValue = resultSet.getString("end_seg");
				if (_returnedStrValue != null && !_returnedStrValue.isEmpty()) {
					allreadyDone = true;
				}
				closeConnection(null, resultSet, prepareStmt);
				if (!allreadyDone) {
					if (firstValidationResult == VvEnums.VERIFICATION_OK.getValue() && sessionStart != "") {
						prepareStmt = conn.prepareStatement(
								"UPDATE crc_schema.ttest SET end_seg=? WHERE process_id=? AND specialist_id=?::uuid AND end_seg IS NULL returning end_seg;--",
								PreparedStatement.RETURN_GENERATED_KEYS);
						prepareStmt.setObject(1, UUID.randomUUID());
						prepareStmt.setLong(2, numeroProceso);
						prepareStmt.setString(3, especialista);
						prepareStmt.executeUpdate();
						resultSet = prepareStmt.getGeneratedKeys();
						while (resultSet != null && resultSet.next()) {
							_returnedStrValue = resultSet.getString("end_seg");
						}
					}
				}
				closeConnection(conn, resultSet, prepareStmt);
				if (_returnedStrValue == null || _returnedStrValue.isEmpty()) {
					// Specialist’s test tracking request ID error.
					throw getAuthFault(conn, 12508);
				}
			}

		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex.getMessage());
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return _returnedStrValue;
	}

	/*
	 * 5 - solicitarResultadoIdentificadorSeguimiento 3.6 process work flow
	 * returns the fingers comparison result
	 */
	public BiometricAuthResult solicitarResultadoIdentificadorSeguimiento(String usuarioServicio,
			String contrasenaServicio, String idSeguimiento) {
		logger.info("Executing operation solicitarResultadoIdentificadorSeguimiento");
		BiometricAuthResult _returned = null;
		BiometricAuthDetails _exceptionDetailsObject = null;
		BiometricAuthDetailsList _exceptionDetailsList = null;
		VvException vvException = null;
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		int codeError = 12511; // default is succeed
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12017);
			}
			prepareStmt = conn.prepareStatement(
					"SELECT estado_ver_start,ver_details_start,estado_ver_end,ver_details_end FROM crc_schema.ttest WHERE start_seg= ?::uuid");
			prepareStmt.setString(1, idSeguimiento);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {

				if (resultSet.getInt("estado_ver_start") == 0) {
					// No fingers verification Specialist’s test start.
					codeError = 12509;
				}
				// CHECK IF FINGERS IDENFICATION FAILS AT THE START BY
				// CRC APP
				if (resultSet.getInt("estado_ver_start") < 0) {
					codeError = resultSet.getInt("ver_details_start");
				}
				// CHECK IF FINGERS IDENFICATION FAILS AT THE END BY CRC
				// APP
				if (resultSet.getInt("estado_ver_start") == 1 && resultSet.getInt("estado_ver_end") < 0) {
					codeError = resultSet.getInt("ver_details_end");
				}
				// IF VERIFICATION OK MUST RETURN OK TOO ?
				vvException = getAuthFault(conn, codeError);
				// QUERY FOR CODE DETAILS
				_exceptionDetailsObject = new BiometricAuthDetails();
				_exceptionDetailsObject.setCodigo(Integer.toString(vvException.getFaultInfo().getErrorCode()));
				_exceptionDetailsObject.setMensaje(vvException.getFaultInfo().getErrorMessage());
				_exceptionDetailsList = new BiometricAuthDetailsList();
				_exceptionDetailsList.getEntidadResultadoSeguimientoDetalle().add(_exceptionDetailsObject);
				_returned = new BiometricAuthResult();
				_returned.setEstado(resultSet.getInt("estado_ver_start"));
				_returned.setDetalle(_exceptionDetailsList);
			}
			// _returned.setDetalle(resultSet.getString("details_error"));
			if (_returned.equals(null)) {
				// No start Specialist’s test fingers verification
				// result.
				throw getAuthFault(conn, 12509);
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex);
		} finally {
			closeConnection(conn, null, prepareStmt);
		}
		return _returned;
	}

	/*
	 * 3.7. Temporary Registration Examination Method Name
	 * RegistroExamenTemporal ArrayOfEntidadResultadoTemporalExamen - QUESTIONS
	 * AND ANSWERS
	 */
	public long registroExamenTemporal(String usuarioServicio, String contrasenaServicio, String idSeguimiento,
			int estadoExamen, int resultadoExamen, String obervaciones, SpecialistTestResultList detalle) {
		logger.info("Executing operation registroExamenTemporal");
		long returned = 0; // is ok
		/*
		 * checkSQL - COUNT 4 TESTS OF PROCESS FOR CERTIFICATOR
		 */
		Calendar calendar = Calendar.getInstance();
		Date now = calendar.getTime();
		Timestamp currentTimestamp = new Timestamp(now.getTime());
		Gson _gson = new Gson();
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12018);
			}
			prepareStmt = conn.prepareStatement(
					"UPDATE crc_schema.ttest set estado=?,result=?,end_time=?,observations=?,questions_result=?::json WHERE end_seg=?::uuid AND result IS NULL AND estado_ver_start ='1' AND estado_ver_end='1'");
			prepareStmt.setInt(1, estadoExamen);
			prepareStmt.setInt(2, resultadoExamen);
			prepareStmt.setTimestamp(3, currentTimestamp);
			prepareStmt.setString(4, obervaciones);
			prepareStmt.setObject(5, _gson.toJson(detalle));
			prepareStmt.setString(6, idSeguimiento);
			int updated = prepareStmt.executeUpdate();
			if (updated == VvEnums.UPDATED.getValue()) {
				checkAndChangeStateOfProcessForCertificator(conn, idSeguimiento);
			}
			if (updated == VvEnums.NOT_UPDATED.getValue()) {
				// throws error exception
				returned = VvEnums.RESPONSE_BAD.getValue();
			}

		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex);
		} finally {
			closeConnection(conn, null, prepareStmt);
		}
		return returned;
	}

	/*
	 * 3.11. crearSeguimientoCertificador Create Certifying Tracking
	 */
	public String crearSeguimientoCertificador(String usuarioServicio, String contrasenaServicio, long idproceso,
			String idCertificador, String observaciones, int resultadoExamen, String categoriaFinal) {
		logger.info("Executing operation crearSeguimientoCertificador");
		String seguimento = "";
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		boolean bykeBelongsToCombo = false;
		String updateCategoryQuery = "UPDATE crc_schema.tprocess SET certificator_id=?,certificador_seguimiento=?,"
				+ "observations=?,resultado_examen=?,categoria_final=? "
				+ "WHERE process_id=? AND estado='VERPRB' AND certificador_ver !=?"
				+ "RETURNING certificador_seguimiento";
		String updateSegundoCategoryQuery = "UPDATE crc_schema.tprocess SET certificator_id=?,certificador_seguimiento=?,"
				+ "segundo_observations=?,segundo_resultado_examen=?,segundo_categoria_final=? "
				+ "WHERE process_id=? AND estado='VERPRB' AND certificador_ver !=?"
				+ "RETURNING certificador_seguimiento";

		int processComboIndicator = StateStatus.DISABLED.getValue();
		int examenResult1 = VvEnums.DEFAULT.getValue();
		int examenResult2 = VvEnums.DEFAULT.getValue();
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12019);
			}
			/*
			 * CHECK FOR WHAT CATEGORY
			 */
			prepareStmt = conn.prepareStatement(
					"SELECT process_combo,resultado_examen,segundo_resultado_examen,fec_certification,resultado_examen,certificador_seguimiento "
							+ "FROM crc_schema.tprocess " + "WHERE process_id=? AND estado=?");
			prepareStmt.setLong(1, idproceso);
			prepareStmt.setString(2, ProcessStatus.VERPRB.name());
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				processComboIndicator = resultSet.getInt("process_combo");
				examenResult1 = resultSet.getInt("resultado_examen");
				examenResult2 = resultSet.getInt("segundo_resultado_examen");
			}
			closeConnection(null, resultSet, prepareStmt);
			// CHECK IF CATEGORY IS BYKE
			if (categoriaFinal.equals(Category.A1.name()) || categoriaFinal.equals(Category.A2.name())) {
				// THEN CHECK IF PROCESS COMBO
				if (processComboIndicator == VvEnums.COMBO.getValue()) {
					bykeBelongsToCombo = true;
					if (examenResult2 == VvEnums.DEFAULT.getValue()) {
						prepareStmt = conn.prepareStatement(updateSegundoCategoryQuery);
					} else {
						// CANT override field "segundo_resultado_examen"
						// IF ALLREADY EXISTS
						throw getAuthFault(conn, 61633);
					}
				}
				// PROCESS NO COMBO AND ITS BYKE
			}
			if (!bykeBelongsToCombo) {
				// CHECK IF PROCESS COMBO
				if (examenResult1 == VvEnums.DEFAULT.getValue()) {
					prepareStmt = conn.prepareStatement(updateCategoryQuery);
				} else {
					// CANT override field "resultado_examen"
					// IF ALLREADY EXISTS
					throw getAuthFault(conn, 61610);
				}
			}
			prepareStmt.setString(1, idCertificador);
			prepareStmt.setObject(2, UUID.randomUUID());
			prepareStmt.setString(3, observaciones);
			prepareStmt.setInt(4, resultadoExamen);
			prepareStmt.setString(5, categoriaFinal);
			prepareStmt.setLong(6, idproceso);
			prepareStmt.setLong(7, StateStatus.VERIFICATION_FAILED.getValue());
			resultSet = prepareStmt.executeQuery();
			while (resultSet.next()) {
				seguimento = resultSet.getString("certificador_seguimiento");
			}
			if (seguimento.equals(null) || seguimento.isEmpty() || seguimento == "") {
				// NO SESSION ID ERROR
				throw getAuthFault(conn, 61688);
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex.getMessage());
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return seguimento;
	}

	public long seleccionarProcesoPorIdentificacionAspiranteCombo(String usuarioServicio, String contrasenaServicio,
			String tipoIdentificacion, String numeroIdentificacion) {
		logger.info("Executing operation seleccionarProcesoPorIdentificacionAspiranteCombo");
		long returned = Answer.OK.getValue();
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12020);
			}
			prepareStmt = conn.prepareStatement("SELECT max(process_id)  FROM crc_schema.tprocess WHERE num_ident=?");
			prepareStmt.setString(1, numeroIdentificacion);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				returned = resultSet.getLong("process_id");
			}
			if (returned == Answer.OK.getValue()) {
				// throws exception
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex);
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return returned;

	}

	/*
	 * consultarResultadoSeguimientoCertificador 3.12
	 */
	public ConsultarResultadoSeguimientoCertificadorResultado consultarResultadoSeguimientoCertificador(
			String usuarioServicio, String contrasenaServicio, String idSeguimiento) {
		logger.info("Executing operation consultarResultadoSeguimientoCertificador");
		ConsultarResultadoSeguimientoCertificadorResultado _resultReturned = null;
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12021);
			}
			prepareStmt = conn
					.prepareStatement("SELECT * from crc_schema.tprocess WHERE certificador_seguimiento= ?::uuid");
			prepareStmt.setString(1, idSeguimiento);
			resultSet = prepareStmt.executeQuery();
			while (resultSet != null && resultSet.next()) {
				// IF ITS STATUS OF CERTIFICATORS FINGERS VALIDATION NOT
				// PENDING
				// AND PROCESS STATUS = CERPRU
				if (resultSet.getInt("certificador_ver") != Answer.OK.getValue()
						&& resultSet.getString("estado") == ProcessStatus.CERPRU.name()) {
					_resultReturned = new ConsultarResultadoSeguimientoCertificadorResultado();
					_resultReturned.setCodigoResultado(resultSet.getInt("certificador_ver"));
					_resultReturned.setObservacionesResultado(resultSet.getString("observations"));
					_resultReturned.setIdSeguimientoCertificador(resultSet.getString("certificador_seguimiento"));
				}
			}
			if (_resultReturned.equals(null)) {
				// throws exception
			}
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex);
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
		return _resultReturned;

	}

	/*
	 * SeleccionarResultadoCertificador 3.10
	 */
	public SeleccionarResultadoCertificadorResultado seleccionarResultadoCertificador(String usuarioServicio,
			String contrasenaServicio, long idProceso) {
		logger.info("Executing operation seleccionarResultadoCertificador");
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		try {
			SeleccionarResultadoCertificadorResultado _returned = null;
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				throw getAuthFault(conn, 12022);
			}
			_returned = new SeleccionarResultadoCertificadorResultado();
			if (_returned.equals(null)) {
				// throws exception null
			}
			return _returned;
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex);
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}

	}

	/*
	 * registroReporteFavorable 3.8
	 */
	public boolean registroReporteFavorable(String usuarioServicio, String contrasenaServicio, String idSeguimiento,
			String nombreReporte, byte[] reporte) {
		logger.info("Executing operation registroReporteFavorable");
		Connection conn = null;
		PreparedStatement prepareStmt = null;
		ResultSet resultSet = null;
		try {
			conn = dataSource.getConnection();
			InitialCrcData crcData = new InitialCrcData();
			crcData.setCrcUser(usuarioServicio);
			crcData.setCrcPass(contrasenaServicio);
			if (!validateCRC(conn, crcData)) {
				ErrorDetailsBean faultBean = new ErrorDetailsBean();
				faultBean.setErrorCode(12018);
				faultBean.setErrorMessage("crc authentication error");
				throw new VvException("Authentication service fault", faultBean);
			}
			boolean _return = false;
			return _return;
		} catch (Exception ex) {
			System.out.println(ex);
			throw new RuntimeException(ex);
		} finally {
			closeConnection(conn, resultSet, prepareStmt);
		}
	}

}
